# Generated by Django 5.1.3 on 2024-12-04 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('person_id', models.AutoField(db_column='person_id', primary_key=True, serialize=False)),
                ('identification', models.CharField(db_column='identification', max_length=20)),
                ('first_name', models.CharField(db_column='first_name', max_length=100)),
                ('second_name', models.CharField(blank=True, db_column='second_name', max_length=100, null=True)),
                ('first_last_name', models.CharField(db_column='first_last_name', max_length=100)),
                ('second_last_name', models.CharField(blank=True, db_column='second_last_name', max_length=100, null=True)),
                ('date_of_birth', models.DateField(db_column='date_of_birth')),
                ('phone_number', models.CharField(blank=True, db_column='phone_number', max_length=100, null=True)),
                ('email', models.EmailField(db_column='email', max_length=254)),
                ('send_email', models.BooleanField(db_column='send_email', default=False)),
                ('creation_date', models.DateTimeField(auto_now_add=True, db_column='creation_date')),
                ('modification_date', models.DateTimeField(auto_now=True, db_column='modification_date')),
            ],
            options={
                'verbose_name': 'Person',
                'verbose_name_plural': 'People',
                'db_table': 'People',
                'unique_together': {('identification', 'email')},
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.AutoField(db_column='user_id', primary_key=True, serialize=False)),
                ('username', models.CharField(db_column='username', max_length=100)),
                ('password_hash', models.CharField(db_column='password_hash', max_length=255)),
                ('is_locked', models.BooleanField(db_column='is_locked', default=False)),
                ('is_active', models.BooleanField(db_column='is_active', default=False)),
                ('creation_date', models.DateTimeField(auto_now_add=True, db_column='creation_date')),
                ('modification_date', models.DateTimeField(auto_now=True, db_column='modification_date')),
                ('person_id', models.ForeignKey(db_column='person_id', on_delete=django.db.models.deletion.CASCADE, to='users.people')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'Users',
            },
        ),
    ]
