# Generated by Django 5.1.3 on 2024-12-04 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permissions',
            fields=[
                ('permission_cod', models.CharField(db_column='permission_cod', max_length=3, primary_key=True, serialize=False)),
                ('permission_name', models.CharField(db_column='permission_name', max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Permission',
                'verbose_name_plural': 'Permissions',
                'db_table': 'Permissions',
            },
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('role_id', models.AutoField(db_column='role_id', primary_key=True, serialize=False)),
                ('role_name', models.CharField(db_column='role_name', max_length=100)),
                ('role_description', models.CharField(db_column='role_description', max_length=255)),
                ('campus_id', models.ForeignKey(db_column='campus_id', on_delete=django.db.models.deletion.CASCADE, to='bookings.campus')),
            ],
            options={
                'verbose_name': 'Role',
                'verbose_name_plural': 'Roles',
                'db_table': 'Roles',
            },
        ),
        migrations.CreateModel(
            name='RolePermissions',
            fields=[
                ('role_permission_id', models.AutoField(db_column='role_permission_id', primary_key=True, serialize=False)),
                ('permission_cod', models.ForeignKey(db_column='permission_cod', on_delete=django.db.models.deletion.CASCADE, to='security.permissions')),
                ('role_id', models.ForeignKey(db_column='role_id', on_delete=django.db.models.deletion.CASCADE, to='security.roles')),
            ],
            options={
                'verbose_name': 'Role Permission',
                'verbose_name_plural': 'Role Permissions',
                'db_table': 'RolePermissions',
                'unique_together': {('role_id', 'permission_cod')},
            },
        ),
        migrations.CreateModel(
            name='UserRoles',
            fields=[
                ('user_role_id', models.AutoField(db_column='user_role_id', primary_key=True, serialize=False)),
                ('role_id', models.ForeignKey(db_column='role_id', on_delete=django.db.models.deletion.CASCADE, to='security.roles')),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='users.users')),
            ],
            options={
                'verbose_name': 'User Role',
                'verbose_name_plural': 'User Roles',
                'db_table': 'UserRoles',
                'unique_together': {('user_id', 'role_id')},
            },
        ),
    ]
