# Generated by Django 5.1.3 on 2024-12-04 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('campus_id', models.AutoField(db_column='campus_id', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', max_length=100)),
                ('address', models.CharField(db_column='address', max_length=150)),
                ('phone', models.CharField(db_column='phone', max_length=15)),
                ('email', models.EmailField(db_column='email', max_length=254)),
            ],
            options={
                'verbose_name': 'Campus',
                'verbose_name_plural': 'Campus',
                'db_table': 'Campus',
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('booking_id', models.AutoField(db_column='booking_id', primary_key=True, serialize=False)),
                ('people_amount', models.IntegerField(db_column='people_amount')),
                ('booking_date', models.DateField(db_column='booking_date')),
                ('booking_hour', models.TimeField(db_column='booking_hour')),
                ('observations', models.TextField(blank=True, db_column='observations', null=True)),
                ('active', models.BooleanField(db_column='active', default=True)),
                ('approved', models.BooleanField(db_column='approved', default=False)),
                ('creation_date', models.DateTimeField(auto_now_add=True, db_column='creation_date')),
                ('person_id', models.ForeignKey(db_column='person_id', on_delete=django.db.models.deletion.CASCADE, to='users.people')),
                ('campus_id', models.ForeignKey(db_column='campus_id', on_delete=django.db.models.deletion.CASCADE, to='bookings.campus')),
            ],
            options={
                'verbose_name': 'Booking',
                'verbose_name_plural': 'Bookings',
                'db_table': 'Booking',
            },
        ),
    ]
